### ISSUE TITLE
cart.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [carolineyanko/angular-2-plus-training#2]
Я бы рекоммендовал для обработчиков событий использовать префикс on
addProductQuantity => onAddProductQuantity

Тогда класс будет еще более читаемым
методы ng... (хуки)
методы on... (обратчики событий)
публичные методы (где-то используются в темплейте)
приватные методы (не используются в темплейте)

**Comment by karolinayanko** [comment]
Fixed
